export const INITIAL_ITEMS = [
  {
    id: 1,
    name: "Veg Burger",
    price: 50,
    category: "Snacks",
    dietary: "Veg",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    description: "Classic veggie patty with fresh lettuce and sauce.",
    calories: 350,
    protein: "12g",
    allergens: ["Gluten", "Dairy"],
    tags: ["Vegetarian"]
  },
  {
    id: 2,
    name: "Chicken Sandwich",
    price: 80,
    category: "Snacks",
    dietary: "Non-Veg",
    image: "https://images.unsplash.com/photo-1521305916504-4a1121188589?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    description: "Grilled chicken with mayo and cheese.",
    calories: 450,
    protein: "25g",
    allergens: ["Gluten", "Dairy", "Egg"],
    tags: ["High-Protein", "Non-Veg"]
  },
  {
    id: 3,
    name: "Cold Coffee",
    price: 40,
    category: "Beverages",
    dietary: "Veg",
    image: "https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    description: "Chilled brewed coffee with ice cream.",
    calories: 220,
    protein: "5g",
    allergens: ["Dairy"],
    tags: ["Vegetarian", "Sweet"]
  },
  {
    id: 4,
    name: "Masala Dosa",
    price: 60,
    category: "Breakfast",
    dietary: "Veg",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    description: "Crispy crepe with spiced potato filling.",
    calories: 300,
    protein: "6g",
    allergens: [],
    tags: ["Vegan", "Gluten-Free"]
  },
  {
    id: 5,
    name: "Rajma Rice Bowl",
    price: 90,
    category: "Lunch",
    dietary: "Veg",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    description: "Comforting kidney beans curry with steamed rice.",
    calories: 400,
    protein: "14g",
    allergens: [],
    tags: ["Vegan", "High-Fiber"]
  },
  {
    id: 11,
    name: "Samosa (2 pcs)",
    price: 30,
    category: "Snacks",
    dietary: "Veg",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=60",
    description: "Crispy pastry filled with spiced potatoes.",
    calories: 250,
    protein: "4g",
    allergens: ["Gluten"],
    tags: ["Spicy", "Vegan"]
  },
  {
    id: 12,
    name: "Veg Cutlet",
    price: 25,
    category: "Snacks",
    dietary: "Veg",
    image: "https://images.unsplash.com/photo-1522299836371-d6872718e873?w=500&auto=format&fit=crop&q=60",
    description: "Spiced vegetable patties, fried to perfection.",
    calories: 200,
    protein: "5g",
    allergens: ["Gluten"],
    tags: ["Spicy", "Vegetarian"]
  },
  {
    id: 13,
    name: "Lays - Classic Salted",
    price: 20,
    category: "Packaged",
    dietary: "Veg",
    image: "https://images.unsplash.com/photo-1566478919030-4151834f71f9?w=500&auto=format&fit=crop&q=60",
    description: "Classic salted potato chips.",
    calories: 160,
    protein: "2g",
    allergens: [],
    tags: ["Crispy", "Vegetarian"]
  },
  {
    id: 14,
    name: "Kurkure - Masala Munch",
    price: 20,
    category: "Packaged",
    dietary: "Veg",
    image: "https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=500&auto=format&fit=crop&q=60",
    description: "Spicy and crunchy Indian tea-time snack.",
    calories: 180,
    protein: "2g",
    allergens: [],
    tags: ["Spicy", "Vegetarian"]
  },
  {
    id: 15,
    name: "Chicken Meat Roll",
    price: 45,
    category: "Snacks",
    dietary: "Non-Veg",
    image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=500&auto=format&fit=crop&q=60",
    description: "Spiced chicken filling rolled in paratha.",
    calories: 350,
    protein: "15g",
    allergens: ["Gluten", "Dairy"],
    tags: ["Spicy", "Non-Veg"]
  },
  {
    id: 16,
    name: "Fruit Fizz",
    price: 35,
    category: "Beverages",
    dietary: "Veg",
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=500&auto=format&fit=crop&q=60",
    description: "Refreshing sparkling fruit drink.",
    calories: 120,
    protein: "0g",
    allergens: [],
    tags: ["Sweet", "Vegan"]
  },
  {
    id: 17,
    name: "Masala Chai",
    price: 15,
    category: "Beverages",
    dietary: "Veg",
    image: "https://images.unsplash.com/photo-1576092768241-dec231847233?w=500&auto=format&fit=crop&q=60",
    description: "Traditional Indian spiced milk tea.",
    calories: 80,
    protein: "2g",
    allergens: ["Dairy"],
    tags: ["Hot", "Vegetarian"]
  },
  {
    id: 18,
    name: "Hot Coffee",
    price: 20,
    category: "Beverages",
    dietary: "Veg",
    image: "https://images.unsplash.com/photo-1520986606214-8b456906c813?w=500&auto=format&fit=crop&q=60",
    description: "Freshly brewed hot coffee.",
    calories: 90,
    protein: "2g",
    allergens: ["Dairy"],
    tags: ["Hot", "Vegetarian"]
  },
  {
    id: 19,
    name: "Dairy Milk Chocolate",
    price: 40,
    category: "Packaged",
    dietary: "Veg",
    image: "https://images.unsplash.com/photo-1548848221-0c2e497ed557?w=500&auto=format&fit=crop&q=60",
    description: "Smooth and creamy milk chocolate.",
    calories: 200,
    protein: "3g",
    allergens: ["Dairy"],
    tags: ["Sweet", "Vegetarian"]
  },
  {
    id: 20,
    name: "KitKat",
    price: 25,
    category: "Packaged",
    dietary: "Veg",
    image: "https://images.unsplash.com/photo-1627041846618-205193910c59?w=500&auto=format&fit=crop&q=60",
    description: "Crispy wafer fingers covered in chocolate.",
    calories: 180,
    protein: "2g",
    allergens: ["Dairy", "Gluten"],
    tags: ["Sweet", "Vegetarian"]
  }
];
